In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection  import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# data
def create_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['label'] = iris.target
    df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
    data = np.array(df.iloc[:100, [0, 1, -1]])
    for i in range(len(data)):
        if data[i,-1] == 0:
            data[i,-1] = -1
    # print(data)
    return data[:,:2], data[:,-1]

In [8]:
X, y = create_data()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [4]:
X.shape

(100, 2)

In [9]:
X[:10]

array([[ 5.1,  3.5],
       [ 4.9,  3. ],
       [ 4.7,  3.2],
       [ 4.6,  3.1],
       [ 5. ,  3.6],
       [ 5.4,  3.9],
       [ 4.6,  3.4],
       [ 5. ,  3.4],
       [ 4.4,  2.9],
       [ 4.9,  3.1]])

In [10]:
X = np.arange(10).reshape(10, 1)

In [11]:
X.shape

(10, 1)

In [12]:
X[:10]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
y = np.array([1, 1, 1, -1, -1, -1, 1, 1, 1, -1])

In [16]:
features = X[:, 0]
features

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
learning_rate = 0.5

In [20]:
# 单维features
features_min = min(features)
features_max = max(features)
n_step = (features_max - features_min + learning_rate) // learning_rate

In [23]:
print(features_min, '\n', features_max,'\n', n_step)

0 
 9 
 19.0


In [24]:
95 // 5 # 取商，整除操作

19

In [25]:
95 % 5 # 取余

0

In [26]:
95 / 5 

19.0

`_G(self, features, labels, weights)`针对一个特征，函数返回最佳的阈值，并计算分类